config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  get "pages", to: "pages#home"
  get "about", to: "pages#about",as: "about"

  get "myBookings", to: "bookings#my_bookings", as: "my_bookings"

  resources :boats, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :destroy]
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boat.rb
class Boat < ApplicationRecord
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings
  has_many :users, through: :bookings
  has_many :reviews

  include PgSearch::Model
  pg_search_scope :search_by_category,
  against: [ :category ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

  scope :search_by_category, ->(category) { where(category: category) if category.present? }


end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :boat
  #validates :rating, presence: true, numericality: { only_integer: true, message: "must be an integer !" }
  def display_rating
    "#{rating}/10"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
  has_many :bookings
  has_many :boats, through: :bookings
  has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :picture])
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    @boats= Boat.all
    if params[:query]
      @boats = Boat.search_by_category(params[:query])
    end

    if params[:query] == "All"
      @boats = Boat.all
    else
      @boats = Boat.search_by_category(params[:query])
    end

    if @boats.empty?
      flash.now[:notice] = "No boats found for the selected category."
    end
    
    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {boat: boat}),
        marker_html: render_to_string(partial: "marker", locals: {boat: boat})
      }
    end
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boat_params)
    if @boat.save
      redirect_to boat_path(@boat), notice: 'Boat was sucessfully created'
    else
      render :new, status: :unprocessable_entity
    end

  end

  def show
    @boat = Boat.find(params[:id])
    @booking = Booking.new
    @reviews = @boat.reviews
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :description, :category, :price, :address, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
      @booking = Booking.new(booking_params)
      @booking.user = current_user
      @booking.boat = Boat.find(params[:boat_id])

      if @booking.save
        redirect_to boat_path(@booking.boat), notice: 'Booking was sucessfully processed'
      else
        render :new, status: :unprocessable_entity
      end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
      if @booking.update(booking_params)
        redirect_to @booking
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to boat_bookings_path, status: :see_other
  end

  def my_bookings
    @bookings = Booking.where(user: current_user)
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @user = current_user
  end

  def about
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @review.boat = Boat.find(params[:boat_id])

    if @review.save
      redirect_to boat_path(@review.boat), notice: 'review was sucessfully created'
    else
      render :new, alert: "Story was successfully destroyed."


    end
  end



  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/_info_window.html.erb
<p><strong><%= boat.name.capitalize %></strong></p>
<p><%= boat.price %></p>

app/views/boats/_marker.html.erb
<span class='price-tag'>$<%= boat.price %></span>

app/views/boats/index.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="text"><strong> BOAT CATALOGUE </strong></h1>
        <p class="lead text-muted">Here is our featured selection from our wide array of boats.</p>
      </div>
    </div>
</section>

<div class="container">
  <%= form_tag boats_path, method: :get, class: "filter-form" do %>
    <%= select_tag :query, options_for_select(['All', 'Cruise Ship', 'Fishing Boat', 'Super Yacht', 'Pirate Ship', 'Motor Yacht'], params[:query]) %>
    <%= submit_tag "Filter", class:"btn btn-sm btn-warning" %>
  <% end %>
</div>

<div class='container'>
  <div style="width: 100%; height: 100vh;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    class="position-relative">
  </div>
</div>





<div class="album py-5">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-2">
        <% @boats.each do |boat| %>
          <div class="col">
            <div class="card shadow-sm">
              <img class="card-img-top" src="<%=cl_image_path boat.photo.key%>"  width="100%" height="250" preserveAspectRatio="xMidYMid slice" focusable="false">
              <div class="card-body">
                <h1 class="card-text text"><strong><%= boat.name.capitalize %></strong></h1>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to "View", boat_path(boat), class:"btn btn-sm btn-outline-warning" %>
                </div>
                  <small class="text-muted"><%= boat.price %> $ / day</small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/boats/new.html.erb
<div class="container">
  <h2>New Listing</h2>

  <%= simple_form_for(@boat) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "Name of boat" }%>
      <%= f.input :description,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "description" }%>
      <%= f.input :category,
                  collection: ["Cruise Ship", "Fishing Boat", "Super Yacht", "Pirate Ship", "Motor Yacht"],
                  required: true,
                  autofocus: true %>
      <%= f.input :address,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "address" }%>
      <%= f.input :price,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "price" }%>
      <%= f.input :photo,
                  required: true %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Save & Publish", class:"btn btn-warning" %>
    </div>
  <% end %>

</div>

app/views/boats/show.html.erb
<div class="card">
  <div class="card-body titles">
    <%= @boat.name.capitalize %>

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button type="button" class="btn btn-outline-warning btn-lg me-md-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Book This Boat !
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">

              <div class="modal-body">
                  <div class="card-body">
                    <div class="input-group input-group-lg titles">
                      <%= simple_form_for [@boat, @booking], data: { controller: 'flatpickr' } do |f| %>
                        <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "start" } }%>
                        <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "end" } }%>
                        <%= f.submit 'Schedule your appointment', class:"btn btn-outline-success" %>
                      <% end %>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>
</div>

<p> </p>

<div class="container">
  <div id="carouselExample" class="carousel slide position-relative">
    <div class="d-flex justify-content-between" style="height: 550px">
      <div class="carousel-inner" style="width: 45%;">
        <div class="carousel-item active">
          <img src="<%=cl_image_path @boat.photo.key%>"  style="" class="d-block w-100"  width="100%" height="550" >
        </div>
        <div class="carousel-item position-relative">
          <img src="<%=cl_image_path @boat.photo.key%>" class="d-block w-100"  width="100%" height="550" >
        </div>
        <div class="carousel-item position-relative">
          <img src="<%=cl_image_path @boat.photo.key%>" class="d-block w-100"  width="100%" height="550" >
        </div>
      </div>
      <div style="width: 55%; background: white; color: black; padding: 8%">
        <h1 style="font-weight: 700"><%= @boat.name %></h1>
        <p><%= @boat.description %></p>
        <div class="d-flex justify-content-between">
          <p><i class="fa-solid fa-money-bill"></i> <%= @boat.price %>$/ day</p>
          <p><i class="fa-solid fa-location-dot"></i> <%= @boat.address %></p>
        </div>

          <hr>
          <h4 style="font-weight: 600">Leave a review</h4>
          <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Review
          </button>

          <!-- Modal -->
          <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title fs-5" id="staticBackdropLabel" style="font-weight: 600">Leave a review</h1>

                </div>
                <div class="modal-body">
                  <%= simple_form_for [@boat, Review.new] do |f|%>
                    <%= f.input :comment %>
                    <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
                    <%= f.submit "send", class:" btn btn-outline-warning" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>

    <div class="position-absolute top-0 end-0">
      <ul class="list-group list-group-horizontal">
        <li class="list-group-item cathegory"><%= @boat.category %></li>
      </ul>
  </div>

  <div>
  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">Comment</th>
        <th scope="col">Review</th>
        <th scope="col">by</th>
      </tr>
    </thead>

    <tbody>

      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.comment %></td>
          <td><%= "#{"⭐" * review.rating}" %></td>
          <td><%= current_user.first_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  
</div>

app/views/bookings/my_bookings.html.erb
<p></p>

<div class="container d-flex justify-content-center">
     <table class="table table-dark table-striped">
        <thead>
          <tr>
            <th scope="col">name of the vessel</th>
            <th scope="col">start date of your booking</th>
            <th scope="col">end date of your booking</th>
            <th scope="col">to cancel your booking</th>
          </tr>
        </thead>

        <tbody>

        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.boat.name %></td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td><%= link_to "Cancel", boat_booking_path(booking.boat, booking),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},  class:'btn btn-outline-danger btn-sm'%></td>
          </tr>
        <% end %>
        </tbody>
      </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Floatyourboat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>


  <script src="boat_filter_controller.js"></script>

    <style>
      @import url('https://fonts.googleapis.com/css2?family=Kanit:wght@100;300;400;600&display=swap');
    </style>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="text">The Team Behind Float Your Boat !</h1>
        <p class="lead text-body-secondary">Float your Boat is brought to you by the students of le Wagon Batch <strong>#1088</strong> </p>
      </div>
    </div>
</section>



<div class="row row-cols-1 row-cols-sm-2 row-cols-sm-3 row-cols-md-4 g-4">
    <div class="col">
      <div class="card shadow-sm">
        <%=image_tag "Rahouti_IDENT-7666.jpg", class:"card-img"%>
        <div class="card-header d-flex justify-content-between align-items-center">
            <h2 class="titles-sm"> Mouna Rahouti </h2>
            <div class="footer-links-cards">
              <a href="https://github.com/mounapython" target="_blank"><i class="fab fa-github"></i></a>
              <a href="https://www.linkedin.com/in/mouna-rahouti-86672823/" target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>
        </div>

          <div class="card-body">
            <p class="card-text">  Mouna has been working in different fields for the last 10 years : finance, urban mobility and outsourcing. She is a graduate of ESSEC Business School with a specialization in finance. Mouna is a mom of two young girls, she enjoys coding, spending quality time with her family and travelling around the globe.</p>
          </div>
      </div>
    </div>

    <div class="col">
      <div class="card shadow-sm">
          <%=image_tag "wagon pic 3.jpg", class:"card-img" %>
          <div class="card-header d-flex justify-content-between align-items-center">
            <h2 class="titles-sm"> Said Zouagui </h2>
            <div class="footer-links-cards">
              <a href="https://github.com/Szouagui" target="_blank"><i class="fab fa-github"></i></a>
              <a href="https://www.linkedin.com/in/said-zouagui-3ba637142" target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>
          </div>

          <div class="card-body">
            <p class="card-text">Overall, my background in project management in construction, coupled with my interest in technology, led me to pursue coding as a valuable skillset. I continue to learn and develop my coding skills, with the goal of creating innovative digital solutions for the construction industry.</p>
          </div>
      </div>
    </div>

    <div class="col">
      <div class="card shadow-sm">
        <%=image_tag "Driss.jpg", class:"card-img" %>

          <div class="card-header d-flex justify-content-between align-items-center">
            <h2 class="titles-sm"> Driss Freah </h2>
            <div class="footer-links-cards">
              <a href="https://github.com/flyingPie23" target="_blank"><i class="fab fa-github"></i></a>
            </div>
          </div>

          <div class="card-body">
            <p class="card-text">As a 19 year old, I'm all about expressing myself through tech and development was the right medium for me, my development adventure started a couple years ago when messing around with a code editor but I didn't take it seriously till I meet the wonderful team of le wagon</p>
          </div>
      </div>
    </div>

    <div class="col">
      <div class="card shadow-sm">

      <%= image_tag "DSC02844.jpg", class:"card-img" %>

      <div class="card-header d-flex justify-content-between align-items-center">
              <h2 class="titles-sm"> Younes Bouchamma </h2>
              <div class="footer-links-cards">
                <a href="https://github.com/YounesBouchamma" target="_blank"><i class="fab fa-github"></i></a>
              </div>
      </div>

        <div class="card-body">
          <p class="card-text">I am Younes bouchamma, I 'am from Oujda and I have 34 years old , I am a quality engineer . and I 'd like to learn coding at le wagon in order to change my career since i knew that with their help ill aquire the skills i need to make it far in the tech and development industry.</p>
        </div>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>
      <span id='element' data-controller="typed"></span>
    </h1>
     <p>Embark on your new and exiting maritime adventure with our wide selections of sea vessels</p>



  <%= link_to "Give Our Boats A Look", boats_path, class:"btn btn btn-warning" %>

  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/3151/3151027.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "List a boat", new_boat_path, class:"btn btn-warning" %>
          </li>
          <li class="nav-item">
            <%= link_to "Selections", boats_path, class:"nav-link px-2 text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Your Bookings", my_bookings_path, class:"nav-link px-2 text-white" %>
          </li>
           <li class="nav-item">
            <%= link_to "About", about_path, class:"nav-link px-2 text-white" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.picture.key %>
              <%= cl_image_tag current_user.picture.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/924/924915.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Settings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-warning"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>